truth = 0.5  # theta
influence_of_friends = 0.5
speed_of_communication = 0.5  # clock speed
flooding_capacity = 25
bot_follower_percentage = 0.15
number_of_nodes = 4000
average_clustering_coefficient = 0.51
edge_creation_probability = 0.7
number_of_simulations = 1
belief_distribution_groups = 7
